name: Format

on:
  push:
    branches: [main]

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Run gofmt
        run: |
          gofmt -w .

      - name: Commit gofmt changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: format go code with gofmt"
